version: "3"
services:
  php:
    image: php:fpm
    volumes:
      - ./htdocs:/htdocs

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./htdocs:/htdocs
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  db:
    image: mysql:latest
    volumes:
      - ./_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    links:
      - db