version: "3"
services:
  php:
    build: ./dckr/php
    volumes:
      - ./htdocs:/var/www/html/
      - ./config/apache2.conf:/etc/apache2/apache2.conf
    links:
      - db
    ports:
      - 8000:80
    environment:
      - NETTE_DEBUG=1

  db:
    image: mysql:latest
    volumes:
      - ./_db:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./config/phpmyadmin_nginx.conf:/etc/nginx.conf
